### ISSUE TITLE
Notification Bar

### ISSUE THREAD

**Issue by goksunonal** [GokBurSen/Timber#5]
Timber (ses dosyası oynatıp saklama) uygulaması çalışırken kaydırarak **arayüzden** kapattım. Fakat sonrasında bildirim çubuğu kısmındaki görüntünün gitmediğini farkettim.

![screenshot_2017-10-14-20-41-08](https://user-images.githubusercontent.com/32015340/31577964-5b01bf6a-b120-11e7-8b54-8cce071c4f26.png)![screenshot_2017-10-14-20-12-16](https://user-images.githubusercontent.com/32015340/31577756-28889ef8-b11d-11e7-817c-0344c9f3a591.png)

Aynı zamanda **arayüzden** kaydırarak kapatırken ses dosyası çalıyorsa bildirim çubuğu kısmında şarkıda durmamış gibi gözüküyor. Fakat durmamış gibi gözükse bile herhangi bir ses dışarı vermiyor.

![screenshot_2017-10-14-20-12-29](https://user-images.githubusercontent.com/32015340/31577772-61fab3e2-b11d-11e7-90e5-3baebaece304.png)

Ondan sonrada bildirim çubuğundan uygulamanın durdur butonu kısmına basarsanız uygulamayı yeniden açıp kaldığınız ses dosyasına değil farklı bir ses dosyasından devam ediyor. Ondan sonra yürütme sırası ufak bir bozuntu yaşıyor çünkü önceki çaldığın ses dosyasına dönemiyor.

Platform: Android 5.0.2

**Comment by cagdasgerede** [comment]
Assign edilmemiş.
