### ISSUE TITLE
Oynatma Sırası

### ISSUE THREAD

**Issue by goksunonal** [GokBurSen/Timber#9]
Add queue butonunu kullanarak oynatma sırasına ses dosyaları ekliyoruz. Fakat yanlışlıkla eklersek oynatma  sırasında en iyi , en başa koyup ilerletirsek dinlemeden geçebiliriz. Bunu engellemek için oynatma sırasından çıkar özelliğine ihtiyacımız var. Ek olarak tüm oynatma sırasını temizlemeye de ihtiyacımız olabilir.

**Comment by cagdasgerede** [comment]
Assign edilmemiş.

Metinde yazım hataları var. Tekrar gözden geçirin.
